sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tCn8dNZKRMo6JvK4Bby
    access-key-secret: XIeKaJCMYPEyErz8BYVtGfAnoofgNb
    bucket-name: sky-take-out-fun
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10 # 默认0
  wechat:
    appid: wx7598832b029bb7ea
    secret: 91b16387e365b2790c9763de1fc6c5ce

    sky:
      wechat:
        appid: wx7598832b029bb7ea
        secret: 91b16387e365b2790c9763de1fc6c5ce
        mchid: 15651630872
        mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
        privateKeyFilePath: D:\apiclient_key.pem
        apiV3Key: CZBK51236435wxpay435434323FFDuv3
        weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
        notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
        refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php


#  s3:
#    region: Europe (Ireland) eu-west-1
#    access-key-id: AKIA45Y2RPMDNN4CUJP4
#    access-key-secret: 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
#    bucket-name: sky-take-out-fun

